/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    '[...all]': typeof import('./pages/[...all].vue')['default']
    '[name]': typeof import('./pages/hi/[name].vue')['default']
    About: typeof import('./pages/about.md')['default']
    Card: typeof import('./components/ui/card/Card.vue')['default']
    CardContent: typeof import('./components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./components/ui/card/CardHeader.vue')['default']
    CardImage: typeof import('./components/ui/card/CardImage.vue')['default']
    CardTitle: typeof import('./components/ui/card/CardTitle.vue')['default']
    Components: typeof import('./pages/product-list-with-cart/components.vue')['default']
    Notes: typeof import('./pages/product-list-with-cart/notes.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    PageLead: typeof import('./components/PageLead.vue')['default']
    Pages: typeof import('./pages/index.vue')['default']
    ProductListAddToCartButton: typeof import('./projects/product-list-with-cart/components/ProductListAddToCartButton.vue')['default']
    ProductListButton: typeof import('./projects/product-list-with-cart/components/ProductListButton.vue')['default']
    ProductListCart: typeof import('./projects/product-list-with-cart/components/ProductListCart.vue')['default']
    ProductListEmptyCard: typeof import('./projects/product-list-with-cart/components/ProductListEmptyCard.vue')['default']
    ProductListEmptyCart: typeof import('./projects/product-list-with-cart/components/ProductListEmptyCart.vue')['default']
    ProductListHeader: typeof import('./projects/product-list-with-cart/components/ProductListHeader.vue')['default']
    ProductLIstProductCard: typeof import('./projects/product-list-with-cart/components/ProductLIstProductCard.vue')['default']
    ProductListProductsContainer: typeof import('./projects/product-list-with-cart/components/ProductListProductsContainer.vue')['default']
    ProductListWithCart: typeof import('./projects/product-list-with-cart/index.vue')['default']
    'ProductListWithCart.layout': typeof import('./projects/product-list-with-cart/product-list-with-cart.layout.vue')['default']
    ProjectList: typeof import('./components/ProjectList.vue')['default']
    ProjectListItem: typeof import('./components/ProjectListItem.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./components/SideMenu.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TopMenu: typeof import('./components/TopMenu.vue')['default']
  }
}
