/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/hi/[name]': RouteRecordInfo<'/hi/[name]', '/hi/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/product-list-with-cart/': RouteRecordInfo<'/product-list-with-cart/', '/product-list-with-cart', Record<never, never>, Record<never, never>>,
    '/product-list-with-cart/components': RouteRecordInfo<'/product-list-with-cart/components', '/product-list-with-cart/components', Record<never, never>, Record<never, never>>,
    '/product-list-with-cart/notes': RouteRecordInfo<'/product-list-with-cart/notes', '/product-list-with-cart/notes', Record<never, never>, Record<never, never>>,
    '/project-list/': RouteRecordInfo<'/project-list/', '/project-list', Record<never, never>, Record<never, never>>,
  }
}
